logging:
  level:
    root: INFO
  file:
    path: ./logs/auth-service.log

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8084
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/auth/v3/api-docs

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dyw1014@gachon.ac.kr
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  data:
    redis:
      repositories:
        enabled: true
      host: ${REDIS_HOST}
      port: 6379
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MY_SQL_HOST}:3306/adore
    username: ${MY_SQL_USER}
    password: ${MY_SQL_PASSWORD}
  application:
    name: auth-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
jwt:
  access_exp: 86400
  refresh_exp: 1209600
  secret: ${JWT_SECRET}