cluster.name: "elasticsearch"

network.host: 0.0.0.0
discovery.type: single-node
xpack:
  monitoring:
    collection:
      enabled: true
  security:
    transport:
      ssl:
        enabled: false
    http:
      ssl:
        enabled: false
    enabled: false
    enrollment:
      enabled: false