services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - '--collector.systemd'
      - '--collector.processes'
    ports:
      - "9100:9100"
    networks:
      - msa-network
  influxdb:
    image: bitnami/influxdb:1.8.5
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8085:8088"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUXDB_ADMIN_USER_PASSWORD}
      - INFLUXDB_ADMIN_USER_TOKEN=${INFLUXDB_ADMIN_USER_TOKEN}
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=adore
    networks:
      - msa-network
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./k6:/scripts
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus
    networks:
      - msa-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboard:/dashboard
    restart: always
    networks:
      - msa-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - ./prometheus/data:/prometheus
    ports:
      - '9090:9090'
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - msa-network
  # Eureka
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    image: dyw1014/adore-be-discovery-service:latest
    volumes:
      - ./logs:/logs
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8761:8761"
    networks:
      - msa-network

  # Gateway
  gateway-service-local:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    volumes:
      - ./logs:/logs
      - /cert:/ssl
    environment:
      - TZ=Asia/Seoul
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_PROFILES_ACTIVE=local
      - SSL_PASSWORD=${SSL_PASSWORD}
    image: dyw1014/adore-be-gateway-service:latest
    ports:
      - "8111:8111"
    networks:
      - msa-network

  gateway-service-prod:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    volumes:
      - ./logs:/logs
      - /cert:/ssl
    environment:
      - TZ=Asia/Seoul
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_PROFILES_ACTIVE=prod
      - SSL_PASSWORD=${SSL_PASSWORD}
    image: dyw1014/adore-be-gateway-service:latest
    ports:
      - "443:443"
    networks:
      - msa-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    image: dyw1014/adore-be-user-service:latest
    environment:
      - DISCOVERY_SERVICE=http://discovery-service:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - MY_SQL_HOST=${MY_SQL_HOST}
      - MY_SQL_USER=${MY_SQL_USER}
      - MY_SQL_PASSWORD=${MY_SQL_PASSWORD}
    depends_on:
      - discovery-service
    networks:
      - msa-network
    ports:
      - "8081:8081"

  es-service:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es-service
    environment:
      - ELASTIC_PASSWORD=root
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/backup:/usr/share/elasticsearch/backup
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - msa-network

  kibana-service:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - msa-network

  fluentd-service:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    container_name: fluentd-service
    volumes:
      - ./fluentd/pos:/var/pos
      - ./logs:/var/log
      - ./fluentd/buffer:/var/buffer
    image: dyw1014/adore-be-fluentd:latest
    environment:
      - FLUENTD_CONF=fluentd.conf
      - TZ=Asia/Seoul
    networks:
      - msa-network
    ports:
      - "8999:8999"
      - "8999:8999/udp"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    image: dyw1014/adore-be-auth-service:latest
    volumes:
      - ./logs:/logs
    environment:
      - DISCOVERY_SERVICE=http://discovery-service:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - MY_SQL_HOST=${MY_SQL_HOST}
      - MY_SQL_USER=${MY_SQL_USER}
      - MY_SQL_PASSWORD=${MY_SQL_PASSWORD}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - discovery-service
    networks:
      - msa-network
    ports:
      - "8084:8084"

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    container_name: admin-service
    image: dyw1014/adore-be-admin-service:latest
    volumes:
      - ./logs:/logs
    environment:
      - DISCOVERY_SERVICE=http://discovery-service:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - MY_SQL_HOST=${MY_SQL_HOST}
      - MY_SQL_USER=${MY_SQL_USER}
      - MY_SQL_PASSWORD=${MY_SQL_PASSWORD}
    depends_on:
      - discovery-service
    networks:
      - msa-network
    ports:
      - "8083:8083"

networks:
  msa-network:
    driver: bridge
    external: true
