server:
  port: 8111
logging:
  level:
    root: INFO
  file:
    path: ./logs/gateway-service.log

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}

jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    initial-instance-info-replication-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls[0]:
      name: Auth Service
      url: http://localhost:8111/auth/swagger-ui
    urls[1]:
      name: Admin Service
      url: http://localhost:8111/admin/swagger-ui
    path: /auth/swagger-ui

spring:

  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "https://gachon-adore.duckdns.org"
              - "http://localhost"
            allow-credentials: true
            allowedHeaders:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/admin/(?<segment>.*), /api/admin/${segment}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/${segment}
            - AddResponseHeader=Access-Control-Expose-Headers, Set-Cookie
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /api/user/${segment}
            - AddResponseHeader=Access-Control-Expose-Headers, Set-Cookie