logging:
  level:
    root: INFO
  file:
    path: ./logs/gateway-service.log

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}

jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    initial-instance-info-replication-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls[0]:
      name: Auth Service
      url: http://localhost:8111/auth/swagger-ui
    urls[1]:
      name: Admin Service
      url: http://localhost:8111/admin/swagger-ui
    path: /auth/swagger-ui

spring:

  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://gachon-adore.duckdns.org"
              - "http://localhost:5173"
              - "https://gachon-adore.duckdns.org"
              - "https://localhost:5173"
              - "http://localhost"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /admin/${segment}
            - name: JwtFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /auth/${segment}
            - AddResponseHeader=Access-Control-Expose-Headers, Set-Cookie

--- # local
server:
  port: 8111
spring:
  config:
    activate:
      on-profile: local

--- # prod
server:
  ssl:
    enabled: true
    key-store: /ssl/keystore.p12
    key-store-password: ${SSL_PASSWORD}
    key-store-type: PKCS12
  port: 443
spring:
  config:
    activate:
      on-profile: prod