logging:
  level:
    root: INFO
  file:
    path: ./logs/gateway-service.log
jwt:
  secret: "sceretsecretsecretsecretsecretsecretsecretsecretsecretsecret"
  access_exp: 259200
  refresh_exp: 8640000
server:
  port: 8111
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    initial-instance-info-replication-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  data:
    redis:
      repositories:
        enabled: true
      host: ${REDIS_HOST}
      port: 6379
  r2dbc:
    url: r2dbc:mariadb://${MY_SQL_HOST}:3306/adore
    username: ${MY_SQL_USER}
    password: ${MY_SQL_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: dyw1014@gachon.ac.kr
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id : user-service
          uri : lb://user-service
          predicates:
            - Path=/user/**
        - id: community-service
          uri : lb://community-service
          predicates:
            - Path=/community/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**