global:
  scrape_interval: 15s
  scrape_timeout: 15s

  external_labels:
    monitor: 'adore-monitor'
  query_log_file: saved.log

scrape_configs:
  - job_name: 'gateway-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'
    static_configs:
      - targets: [ 'gateway-service:8111' ]
        labels:
          service: 'monitor-1'
  - job_name: 'auth-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'
    static_configs:
      - targets: ['auth-service:8084']
        labels:
          service : 'monitor-1'
  - job_name: 'discovery-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'
    static_configs:
      - targets: [ 'discovery-service:8761' ]
        labels:
          service: 'monitor-1'
  - job_name: 'user-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'
    static_configs:
      - targets: [ 'user-service:8081' ]
        labels:
          service: 'monitor-1'
  - job_name: 'admin-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'
    static_configs:
      - targets: [ 'admin-service:8083' ]
        labels:
          service: 'monitor-1'