logging:
  level:
    root: INFO
  file:
    path: ./logs/admin-service.log
server:
  port: 8083
springdoc:
  api-docs:
    enabled: true
    path: /admin/swagger-ui
    version: openapi_3_1
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
spring:
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MY_SQL_HOST}:3306/adore
    username: ${MY_SQL_USER}
    password: ${MY_SQL_PASSWORD}
  application:
    name: admin-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}